// Product models JDHub stocks. Each model expands into several graded listings
// (see `buildListings` in catalog.ts).
//
// Prices are naira for a "Great"-grade unit, anchored to October 2026 Nigerian
// retailer and marketplace asking prices (Ziggatech, Kara, SLOT, Jumia, Jiji,
// NaijaTechGuide, Luxurycars.ng, Nairametrics). They move with the exchange
// rate, so treat them as a starting point for the owner to adjust in the admin.
//
// Photos are freely licensed images on Wikimedia Commons, credited on each
// product page and on /credits.

import type { ArtKind, CategorySlug } from "./catalog";

export type Model = {
  slug: string;
  category: CategorySlug;
  brand: string;
  name: string;
  /** Wikimedia Commons file name (the part after `File:`). */
  photo: string;
  art: ArtKind;
  tint: string;
  /** Base price for a Great-grade unit with the first storage/config option. */
  price: number;
  /** Number of listings to generate for this model. */
  stock: number;
  /** Storage or configuration tiers, each adding to the base price. */
  tiers?: { label: string; add: number }[];
  colors?: string[];
  /** Fixed spec line (accessories/gadgets) shown under the name. */
  spec?: string;
  attrs?: Record<string, string>;
  /** Cars only. */
  car?: { year: number; km: [number, number]; origin: "Foreign used" | "Nigerian used"; engine: string };
};

const s = (label: string, add: number) => ({ label, add });

export const models: Model[] = [
  // ---------------------------------------------------------------- Phones
  { slug: "iphone-17-pro-max", category: "phones", brand: "Apple", name: "iPhone 17 Pro Max", photo: "Cosmic_Orange_iPhone_17_Pro_Max.jpg", art: "phone", tint: "#d9783a", price: 2_250_000, stock: 2, tiers: [s("256GB", 0), s("512GB", 260_000), s("1TB", 520_000)], colors: ["Cosmic Orange", "Deep Blue", "Silver"] },
  { slug: "iphone-17", category: "phones", brand: "Apple", name: "iPhone 17", photo: "IPhone_17,_Air,_17_Pro,_and_Pro_max.jpg", art: "phone", tint: "#7ea0c4", price: 1_140_000, stock: 2, tiers: [s("256GB", 0), s("512GB", 200_000)], colors: ["Mist Blue", "Lavender", "Black"] },
  { slug: "iphone-16-pro-max", category: "phones", brand: "Apple", name: "iPhone 16 Pro Max", photo: "Back_view_of_iPhone_16_Pro_Max_Natural_Titanium.jpg", art: "phone", tint: "#8a8378", price: 1_750_000, stock: 3, tiers: [s("256GB", 0), s("512GB", 210_000), s("1TB", 420_000)], colors: ["Natural Titanium", "Desert Titanium", "Black Titanium"] },
  { slug: "iphone-16-pro", category: "phones", brand: "Apple", name: "iPhone 16 Pro", photo: "IPhone_16_Pro_series.jpg", art: "phone", tint: "#b49f86", price: 1_450_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 150_000), s("512GB", 330_000)], colors: ["Desert Titanium", "White Titanium", "Black Titanium"] },
  { slug: "iphone-16", category: "phones", brand: "Apple", name: "iPhone 16", photo: "Back_of_iPhone_16.jpg", art: "phone", tint: "#4a6fa5", price: 988_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 120_000)], colors: ["Ultramarine", "Teal", "Black"] },
  { slug: "iphone-15-pro-max", category: "phones", brand: "Apple", name: "iPhone 15 Pro Max", photo: "IPhone_15_pro_max.jpg", art: "phone", tint: "#8a8378", price: 1_350_000, stock: 4, tiers: [s("256GB", 0), s("512GB", 170_000), s("1TB", 340_000)], colors: ["Natural Titanium", "Blue Titanium", "Black Titanium"] },
  { slug: "iphone-15-pro", category: "phones", brand: "Apple", name: "iPhone 15 Pro", photo: "Apple_iPhone_15_Pro.jpg", art: "phone", tint: "#5d6470", price: 1_050_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 110_000), s("512GB", 230_000)], colors: ["Blue Titanium", "White Titanium", "Natural Titanium"] },
  { slug: "iphone-15", category: "phones", brand: "Apple", name: "iPhone 15", photo: "Back_of_iPhone_15.jpg", art: "phone", tint: "#e8b9c4", price: 708_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 90_000)], colors: ["Pink", "Blue", "Black"] },
  { slug: "iphone-14-pro-max", category: "phones", brand: "Apple", name: "iPhone 14 Pro Max", photo: "Back_of_the_iPhone_14_Pro_Max.jpg", art: "phone", tint: "#4b3d5c", price: 820_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 80_000), s("512GB", 170_000)], colors: ["Deep Purple", "Space Black", "Gold"] },
  { slug: "iphone-14-pro", category: "phones", brand: "Apple", name: "iPhone 14 Pro", photo: "IPhone_14_Pro.jpg", art: "phone", tint: "#4b3d5c", price: 720_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 75_000)], colors: ["Deep Purple", "Silver", "Space Black"] },
  { slug: "iphone-14", category: "phones", brand: "Apple", name: "iPhone 14", photo: "IPhone_14_-_3.jpg", art: "phone", tint: "#1f2630", price: 499_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 55_000)], colors: ["Midnight", "Blue", "Starlight"] },
  { slug: "iphone-13-pro-max", category: "phones", brand: "Apple", name: "iPhone 13 Pro Max", photo: "Apple_iPhone_13_Pro_and_13_Pro_Max.jpg", art: "phone", tint: "#9bb6cf", price: 640_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 60_000)], colors: ["Sierra Blue", "Graphite", "Gold"] },
  { slug: "iphone-13-pro", category: "phones", brand: "Apple", name: "iPhone 13 Pro", photo: "Apple_iPhone_13_Pro.jpg", art: "phone", tint: "#9bb6cf", price: 560_000, stock: 3, tiers: [s("128GB", 0), s("256GB", 55_000)], colors: ["Sierra Blue", "Graphite", "Silver"] },
  { slug: "iphone-13", category: "phones", brand: "Apple", name: "iPhone 13", photo: "IPhone_13.jpg", art: "phone", tint: "#2e4a6b", price: 431_800, stock: 4, tiers: [s("128GB", 0), s("256GB", 45_000)], colors: ["Blue", "Midnight", "Pink"] },
  { slug: "iphone-12-pro-max", category: "phones", brand: "Apple", name: "iPhone 12 Pro Max", photo: "IPhone_12_Pro_Max_-_3.jpg", art: "phone", tint: "#3d5a73", price: 480_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 45_000)], colors: ["Pacific Blue", "Graphite", "Gold"] },
  { slug: "iphone-12-pro", category: "phones", brand: "Apple", name: "iPhone 12 Pro", photo: "IPhone_12_Pro_-_3.jpg", art: "phone", tint: "#3d5a73", price: 420_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 40_000)], colors: ["Pacific Blue", "Silver"] },
  { slug: "iphone-12-mini", category: "phones", brand: "Apple", name: "iPhone 12 mini", photo: "IPhone_12_mini.jpg", art: "phone", tint: "#1f2630", price: 255_000, stock: 2, tiers: [s("64GB", 0), s("128GB", 30_000)], colors: ["Black", "White", "Green"] },
  { slug: "iphone-11-pro-max", category: "phones", brand: "Apple", name: "iPhone 11 Pro Max", photo: "Iphone_11_pro_max.jpg", art: "phone", tint: "#3f4a3c", price: 360_000, stock: 2, tiers: [s("64GB", 0), s("256GB", 40_000)], colors: ["Midnight Green", "Space Grey", "Gold"] },
  { slug: "iphone-11-pro", category: "phones", brand: "Apple", name: "iPhone 11 Pro", photo: "20191227_iPhone_11_Pro_1.jpg", art: "phone", tint: "#3f4a3c", price: 315_000, stock: 2, tiers: [s("64GB", 0), s("256GB", 35_000)], colors: ["Midnight Green", "Silver"] },
  { slug: "iphone-11", category: "phones", brand: "Apple", name: "iPhone 11", photo: "IPhone_11_all_color.jpg", art: "phone", tint: "#c8102e", price: 263_800, stock: 3, tiers: [s("64GB", 0), s("128GB", 42_000)], colors: ["(PRODUCT)RED", "Black", "White", "Purple"] },
  { slug: "iphone-xr", category: "phones", brand: "Apple", name: "iPhone XR", photo: "IPhone_XR.jpg", art: "phone", tint: "#1f1f1f", price: 185_000, stock: 2, tiers: [s("64GB", 0), s("128GB", 25_000)], colors: ["Black", "Blue", "Coral"] },
  { slug: "iphone-se-3", category: "phones", brand: "Apple", name: "iPhone SE (3rd gen)", photo: "Back_of_the_iPhone_SE_(3rd_generation).jpg", art: "phone", tint: "#1f1f1f", price: 175_000, stock: 2, tiers: [s("64GB", 0), s("128GB", 25_000)], colors: ["Midnight", "Starlight", "(PRODUCT)RED"] },
  { slug: "galaxy-s25-ultra", category: "phones", brand: "Samsung", name: "Galaxy S25 Ultra", photo: "Samsung_Galaxy_S25_Ultra.jpg", art: "phone", tint: "#8fa3b8", price: 1_450_000, stock: 3, tiers: [s("256GB", 0), s("512GB", 180_000)], colors: ["Titanium Silverblue", "Titanium Black", "Titanium Gray"] },
  { slug: "galaxy-s24-ultra", category: "phones", brand: "Samsung", name: "Galaxy S24 Ultra", photo: "SAMSUNG_Galaxy_S24_Ultra_(2).jpg", art: "phone", tint: "#5b5e63", price: 1_050_000, stock: 3, tiers: [s("256GB", 0), s("512GB", 150_000)], colors: ["Titanium Gray", "Titanium Black", "Titanium Violet"] },
  { slug: "galaxy-s24", category: "phones", brand: "Samsung", name: "Galaxy S24", photo: "Samsung_Galaxy_S24.jpg", art: "phone", tint: "#c9b8e0", price: 696_800, stock: 2, tiers: [s("128GB", 0), s("256GB", 60_000)], colors: ["Cobalt Violet", "Onyx Black", "Amber Yellow"] },
  { slug: "galaxy-s23-ultra", category: "phones", brand: "Samsung", name: "Galaxy S23 Ultra", photo: "Samsung_S23_Ultra.jpg", art: "phone", tint: "#2b2b2b", price: 780_000, stock: 3, tiers: [s("256GB", 0), s("512GB", 110_000)], colors: ["Phantom Black", "Green", "Cream"] },
  { slug: "galaxy-s23", category: "phones", brand: "Samsung", name: "Galaxy S23", photo: "Back_of_the_Samsung_Galaxy_S23.jpg", art: "phone", tint: "#b7c9b0", price: 520_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 50_000)], colors: ["Green", "Phantom Black", "Lavender"] },
  { slug: "galaxy-s22-ultra", category: "phones", brand: "Samsung", name: "Galaxy S22 Ultra", photo: "SAMSUNG_Galaxy_S22_Ultra_BLACK_(3).jpg", art: "phone", tint: "#1f1f1f", price: 520_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 50_000)], colors: ["Phantom Black", "Burgundy"] },
  { slug: "galaxy-s21-ultra", category: "phones", brand: "Samsung", name: "Galaxy S21 Ultra", photo: "SAMSUNG_Galaxy_S21_Ultra(2).jpg", art: "phone", tint: "#2b2b2b", price: 380_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 40_000)], colors: ["Phantom Black", "Phantom Silver"] },
  { slug: "galaxy-z-fold7", category: "phones", brand: "Samsung", name: "Galaxy Z Fold7", photo: "Samsung_Galaxy_Z_Fold_7_and_Z_Flip_7.jpg", art: "phone", tint: "#2f3b52", price: 1_692_800, stock: 2, tiers: [s("256GB", 0), s("512GB", 200_000)], colors: ["Blue Shadow", "Jetblack", "Silver Shadow"] },
  { slug: "galaxy-z-flip4", category: "phones", brand: "Samsung", name: "Galaxy Z Flip4", photo: "Samsung_Galaxy_Z_Flip_4.jpg", art: "phone", tint: "#c9b8e0", price: 380_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 40_000)], colors: ["Bora Purple", "Graphite", "Pink Gold"] },
  { slug: "galaxy-a55", category: "phones", brand: "Samsung", name: "Galaxy A55 5G", photo: "Samsung_Galaxy_A55_5G_2024.jpg", art: "phone", tint: "#a8c5e0", price: 480_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 45_000)], colors: ["Awesome Iceblue", "Awesome Navy", "Awesome Lilac"] },
  { slug: "galaxy-a54", category: "phones", brand: "Samsung", name: "Galaxy A54 5G", photo: "Back_of_the_Samsung_Galaxy_A54_5G.jpg", art: "phone", tint: "#c7d6a8", price: 330_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 35_000)], colors: ["Awesome Lime", "Awesome Graphite"] },
  { slug: "galaxy-a35", category: "phones", brand: "Samsung", name: "Galaxy A35 5G", photo: "Samsung_Galaxy_A35_5G_2024_(1).jpg", art: "phone", tint: "#24324d", price: 448_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 40_000)], colors: ["Awesome Navy", "Awesome Iceblue"] },
  { slug: "galaxy-a15", category: "phones", brand: "Samsung", name: "Galaxy A15 5G", photo: "Samsung_Galaxy_A15_5G_2024_(1).jpg", art: "phone", tint: "#2b3a55", price: 185_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 25_000)], colors: ["Blue Black", "Light Blue"] },
  { slug: "pixel-9-pro-xl", category: "phones", brand: "Google", name: "Pixel 9 Pro XL", photo: "Google_Pixel_9_Pro_XL_(front).jpg", art: "phone", tint: "#d6cfc4", price: 900_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 80_000)], colors: ["Porcelain", "Obsidian", "Hazel"] },
  { slug: "pixel-8-pro", category: "phones", brand: "Google", name: "Pixel 8 Pro", photo: "Google_Pixel_8_Pro.jpg", art: "phone", tint: "#7fa6c9", price: 600_000, stock: 2, tiers: [s("128GB", 0), s("256GB", 60_000)], colors: ["Bay", "Obsidian", "Porcelain"] },
  { slug: "tecno-camon-40-pro", category: "phones", brand: "Tecno", name: "Camon 40 Pro 5G", photo: "Tecno_Camon_40_Pro_5G.jpg", art: "phone", tint: "#1f2a2a", price: 360_000, stock: 2, tiers: [s("256GB", 0), s("512GB", 45_000)], colors: ["Galaxy Black", "Glacier White", "Emerald Lake Green"] },

  // ----------------------------------------------------------- Accessories
  { slug: "airpods-pro-2", category: "accessories", brand: "Apple", name: "AirPods Pro (2nd gen)", photo: "AirPods_Pro_(2nd_generation).jpg", art: "earbuds", tint: "#f4f4f4", price: 190_000, stock: 3, spec: "USB-C MagSafe case · ANC", attrs: { Compatibility: "iPhone, iPad, Mac, Android (Bluetooth)", "Noise cancelling": "Active (ANC)", Case: "MagSafe, USB-C" } },
  { slug: "airpods-3", category: "accessories", brand: "Apple", name: "AirPods (3rd gen)", photo: "AirPods_3.jpg", art: "earbuds", tint: "#f4f4f4", price: 135_000, stock: 2, spec: "Lightning case · Spatial audio", attrs: { Compatibility: "iPhone, iPad, Mac, Android (Bluetooth)", Case: "Lightning" } },
  { slug: "airpods-2", category: "accessories", brand: "Apple", name: "AirPods (2nd gen)", photo: "AirPods_(2).jpg", art: "earbuds", tint: "#f4f4f4", price: 85_000, stock: 2, spec: "Lightning charging case", attrs: { Compatibility: "iPhone, iPad, Mac, Android (Bluetooth)", Case: "Lightning" } },
  { slug: "airpods-max", category: "accessories", brand: "Apple", name: "AirPods Max", photo: "Apple_AirPods_Max_3.jpg", art: "earbuds", tint: "#d8d8d8", price: 650_000, stock: 2, spec: "Over-ear · ANC · Smart Case", colors: ["Space Grey", "Silver", "Sky Blue"], attrs: { Compatibility: "iPhone, iPad, Mac, Android (Bluetooth)", "Noise cancelling": "Active (ANC)", Battery: "Up to 20 hours" } },
  { slug: "galaxy-buds2-pro", category: "accessories", brand: "Samsung", name: "Galaxy Buds2 Pro", photo: "Samsung_Galaxy_Buds_2_Pro.png", art: "earbuds", tint: "#c9b8e0", price: 120_000, stock: 2, spec: "Bora Purple · ANC · 24-bit Hi-Fi", attrs: { Compatibility: "Galaxy phones (best), any Bluetooth device", "Noise cancelling": "Active (ANC)" } },
  { slug: "galaxy-buds-live", category: "accessories", brand: "Samsung", name: "Galaxy Buds Live", photo: "Samsung_Galaxy_Buds_Live.jpg", art: "earbuds", tint: "#a0522d", price: 60_000, stock: 1, spec: "Open-fit · Mystic Bronze", attrs: { Compatibility: "Any Bluetooth device" } },
  { slug: "jbl-flip-5", category: "accessories", brand: "JBL", name: "JBL Flip 5", photo: "JBL_speaker,_2021.jpg", art: "powerbank", tint: "#2b4c7e", price: 95_000, stock: 2, spec: "Portable Bluetooth speaker · IPX7", attrs: { Battery: "Up to 12 hours", Waterproof: "IPX7" } },
  { slug: "jbl-flip-4", category: "accessories", brand: "JBL", name: "JBL Flip 4", photo: "JBL_Flip_4.jpg", art: "powerbank", tint: "#1f1f1f", price: 70_000, stock: 1, spec: "Portable Bluetooth speaker · IPX7", attrs: { Battery: "Up to 12 hours", Waterproof: "IPX7" } },
  { slug: "anker-powercore-10000", category: "accessories", brand: "Anker", name: "PowerCore 10000", photo: "Anker_power_bank_lit.jpg", art: "powerbank", tint: "#1f1f1f", price: 28_000, stock: 2, spec: "10,000mAh · PowerIQ fast charge", attrs: { Capacity: "10,000mAh", Compatibility: "iPhone, Android, earbuds" } },
  { slug: "anker-powercore-5000", category: "accessories", brand: "Anker", name: "PowerCore 5000", photo: "2023_Powerbank_Anker_Powercore_5000mAh.jpg", art: "powerbank", tint: "#2b2b2b", price: 18_000, stock: 1, spec: "5,000mAh · Pocket size", attrs: { Capacity: "5,000mAh", Compatibility: "iPhone, Android, earbuds" } },
  { slug: "anker-powerport-40w", category: "accessories", brand: "Anker", name: "PowerPort 40W 5-Port", photo: "Anker-PowerPort-40W-5-Port-USB-Ladegeraet.jpg", art: "charger", tint: "#ffffff", price: 32_000, stock: 1, spec: "5 USB ports · Desk charger", attrs: { Output: "40W total", Ports: "5 × USB-A" } },
  { slug: "apple-pencil", category: "accessories", brand: "Apple", name: "Apple Pencil (1st gen)", photo: "Apple_Pencil.jpg", art: "charger", tint: "#ffffff", price: 95_000, stock: 1, spec: "Fits iPad (6th–10th gen), iPad Air 3", attrs: { Compatibility: "iPad 6th–10th gen, iPad Air (3rd gen), iPad mini (5th gen)" } },
  { slug: "airtag", category: "accessories", brand: "Apple", name: "AirTag", photo: "Airtag_-_1.jpg", art: "charger", tint: "#ffffff", price: 38_000, stock: 2, spec: "Find My tracker · 1-pack", attrs: { Compatibility: "iPhone with iOS 14.5+", Battery: "CR2032, user-replaceable" } },
  { slug: "earpods-usb-c", category: "accessories", brand: "Apple", name: "EarPods", photo: "Earpods.jpg", art: "earbuds", tint: "#ffffff", price: 15_000, stock: 1, spec: "Wired · Inline remote", attrs: { Compatibility: "iPhone, iPad" } },
  { slug: "phone-case-clear", category: "accessories", brand: "JDHub", name: "Shockproof Phone Case", photo: "Mobile_phone_cover.jpg", art: "case", tint: "#2c2c2c", price: 12_000, stock: 2, spec: "Fits iPhone 12 – 16 · Galaxy S-series", attrs: { Compatibility: "iPhone 12 – 16, Galaxy S22 – S25 (choose at checkout)" } },
  { slug: "usb-c-cable", category: "accessories", brand: "JDHub", name: "USB-C to USB-C Cable (1m)", photo: "USB_Type-C_plug_20170626.jpg", art: "charger", tint: "#ffffff", price: 9_000, stock: 1, spec: "60W PD · Braided", attrs: { Compatibility: "iPhone 15+, Galaxy, MacBook, iPad" } },

  // --------------------------------------------------------------- Gadgets
  { slug: "macbook-air-m2", category: "gadgets", brand: "Apple", name: 'MacBook Air 13" M2', photo: "M2_Macbook_Air_Midnight_model_-_1.jpg", art: "laptop", tint: "#2e3440", price: 870_000, stock: 3, tiers: [s("8GB · 256GB", 0), s("16GB · 512GB", 260_000)], colors: ["Midnight", "Starlight", "Space Grey"], attrs: { Chip: "Apple M2", Display: '13.6" Liquid Retina', Serial: "Checked" } },
  { slug: "macbook-air-m2-starlight", category: "gadgets", brand: "Apple", name: 'MacBook Air 13" M2 Starlight', photo: "M2_Macbook_Air_Starlight_model.jpg", art: "laptop", tint: "#d8cdb8", price: 880_000, stock: 1, tiers: [s("8GB · 256GB", 0), s("8GB · 512GB", 150_000)], attrs: { Chip: "Apple M2", Display: '13.6" Liquid Retina', Serial: "Checked" } },
  { slug: "macbook-pro-14-m1-pro", category: "gadgets", brand: "Apple", name: 'MacBook Pro 14" M1 Pro', photo: "A_2021_14-inch_Silver_MacBook_Pro.jpg", art: "laptop", tint: "#c0c3c8", price: 1_450_000, stock: 2, tiers: [s("16GB · 512GB", 0), s("16GB · 1TB", 220_000)], attrs: { Chip: "Apple M1 Pro", Display: '14.2" Liquid Retina XDR', Serial: "Checked" } },
  { slug: "dell-xps-13", category: "gadgets", brand: "Dell", name: "Dell XPS 13 (9300)", photo: "Dell_XPS_13_9300.jpg", art: "laptop", tint: "#c0c3c8", price: 650_000, stock: 2, tiers: [s("i7 · 16GB · 512GB", 0)], attrs: { CPU: "Intel Core i7 (10th gen)", Display: '13.4" FHD+', Serial: "Checked" } },
  { slug: "thinkpad-x1-carbon", category: "gadgets", brand: "Lenovo", name: "ThinkPad X1 Carbon", photo: "Lenovo_ThinkPad_X1_Carbon_Ultrabook.jpg", art: "laptop", tint: "#1f1f1f", price: 420_000, stock: 2, tiers: [s("i5 · 8GB · 256GB", 0), s("i7 · 16GB · 512GB", 120_000)], attrs: { Display: '14" FHD', Serial: "Checked" } },
  { slug: "surface-pro-11", category: "gadgets", brand: "Microsoft", name: "Surface Pro (11th Edition)", photo: "Microsoft_Surface_Pro.jpg", art: "tablet", tint: "#b8bcc2", price: 1_600_000, stock: 1, tiers: [s("16GB · 512GB", 0)], attrs: { Chip: "Snapdragon X Plus", Display: '13" PixelSense', Serial: "Checked" } },
  { slug: "ipad-pro-m4", category: "gadgets", brand: "Apple", name: "iPad Pro (M4)", photo: "M4_iPad_Pro_series_-_1.jpg", art: "tablet", tint: "#3a3d42", price: 1_650_000, stock: 2, tiers: [s('11" · 256GB', 0), s('13" · 256GB', 450_000)], attrs: { Chip: "Apple M4", Display: "Ultra Retina XDR (OLED)", Serial: "Checked" } },
  { slug: "ipad-air-4", category: "gadgets", brand: "Apple", name: "iPad Air (4th gen)", photo: "IPad_Air_2020_(51012790753).jpg", art: "tablet", tint: "#8fb3d1", price: 420_000, stock: 2, tiers: [s("64GB · Wi-Fi", 0), s("256GB · Wi-Fi", 70_000)], attrs: { Chip: "A14 Bionic", Display: '10.9" Liquid Retina', Serial: "Checked" } },
  { slug: "ipad-lineup", category: "gadgets", brand: "Apple", name: "iPad mini (6th gen)", photo: "Apple.iPad.jpg", art: "tablet", tint: "#55585d", price: 480_000, stock: 2, tiers: [s("64GB · Wi-Fi", 0), s("256GB · Wi-Fi", 90_000)], attrs: { Chip: "A15 Bionic", Display: '8.3" Liquid Retina', Serial: "Checked" } },
  { slug: "galaxy-tab-s9", category: "gadgets", brand: "Samsung", name: "Galaxy Tab S9", photo: "20230729_삼성_갤럭시_탭_S9.jpg", art: "tablet", tint: "#3a3d42", price: 850_000, stock: 1, tiers: [s("128GB · Wi-Fi", 0)], attrs: { Display: '11" Dynamic AMOLED 2X', "S Pen": "Included", Serial: "Checked" } },
  { slug: "apple-watch-ultra-2", category: "gadgets", brand: "Apple", name: "Apple Watch Ultra 2", photo: "Apple_Watch_Ultra_-_2.jpg", art: "watch", tint: "#b9a98f", price: 750_000, stock: 2, spec: "49mm titanium · GPS + Cellular", attrs: { Case: "49mm titanium", Battery: "Up to 36 hours", Serial: "Checked" } },
  { slug: "apple-watch-series-9", category: "gadgets", brand: "Apple", name: "Apple Watch Series 9", photo: "Apple_Watch_Series_9_(cropped).jpg", art: "watch", tint: "#232323", price: 420_000, stock: 2, tiers: [s("41mm · GPS", 0), s("45mm · GPS", 40_000)], attrs: { Battery: "Up to 18 hours", Serial: "Checked" } },
  { slug: "galaxy-watch", category: "gadgets", brand: "Samsung", name: "Galaxy Watch (46mm)", photo: "SAMSUNG_Galaxy_Watch.jpg", art: "watch", tint: "#232323", price: 120_000, stock: 1, spec: "46mm · Bluetooth · Silver", attrs: { Battery: "Up to 4 days", Serial: "Checked" } },
  { slug: "galaxy-watch-active", category: "gadgets", brand: "Samsung", name: "Galaxy Watch Active", photo: "Samsung_Galaxy_Watch_Active.jpg", art: "watch", tint: "#2b2b2b", price: 85_000, stock: 1, spec: "40mm · Bluetooth · Black", attrs: { Battery: "Up to 45 hours", Serial: "Checked" } },
  { slug: "ps5-disc", category: "gadgets", brand: "Sony", name: "PlayStation 5 (Disc)", photo: "Playstation_5.jpg", art: "console", tint: "#f2f2f2", price: 880_800, stock: 3, spec: "825GB · 1 DualSense controller", attrs: { Storage: "825GB SSD", Edition: "Disc", Serial: "Checked" } },
  { slug: "ps5-bundle", category: "gadgets", brand: "Sony", name: "PlayStation 5 + Extra DualSense", photo: "PlayStation_5_and_DualSense_(2).jpg", art: "console", tint: "#f2f2f2", price: 953_700, stock: 2, spec: "Disc edition · 2 controllers", attrs: { Storage: "825GB SSD", Controllers: "2", Serial: "Checked" } },
  { slug: "xbox-series-x", category: "gadgets", brand: "Microsoft", name: "Xbox Series X", photo: "Xbox_series_X_(50648118708).jpg", art: "console", tint: "#1f1f1f", price: 760_000, stock: 2, spec: "1TB · 4K/120fps", attrs: { Storage: "1TB SSD", Serial: "Checked" } },
  { slug: "xbox-series-s", category: "gadgets", brand: "Microsoft", name: "Xbox Series S", photo: "Xbox_Series_S_with_controller.jpg", art: "console", tint: "#f2f2f2", price: 450_000, stock: 2, spec: "512GB · All-digital", attrs: { Storage: "512GB SSD", Serial: "Checked" } },
  { slug: "switch-oled", category: "gadgets", brand: "Nintendo", name: "Nintendo Switch OLED", photo: "Nintendo_Switch_OLED_Model.jpg", art: "console", tint: "#e60012", price: 480_000, stock: 2, spec: '7" OLED · 64GB', colors: ["Neon Red/Blue", "White"], attrs: { Storage: "64GB", Serial: "Checked" } },
  { slug: "meta-quest-3", category: "gadgets", brand: "Meta", name: "Meta Quest 3", photo: "Meta_Quest_3_front_View.jpg", art: "console", tint: "#f2f2f2", price: 850_000, stock: 1, spec: "128GB · Mixed reality headset", attrs: { Storage: "128GB", Serial: "Checked" } },
  { slug: "dji-mini-4-pro", category: "gadgets", brand: "DJI", name: "DJI Mini 4 Pro", photo: "2024_Dron_DJI_Mini_4_Pro_(01).jpg", art: "drone", tint: "#7d7f82", price: 1_566_000, stock: 2, tiers: [s("RC-N2", 0), s("Fly More Combo (RC 2)", 340_000)], attrs: { Video: "4K/60fps HDR", "Flight time": "34 min", Serial: "Checked" } },
  { slug: "dji-mini-3-pro", category: "gadgets", brand: "DJI", name: "DJI Mini 3 Pro", photo: "Drone_dji_mini_3_pro.jpg", art: "drone", tint: "#7d7f82", price: 1_050_000, stock: 1, tiers: [s("DJI RC", 0)], attrs: { Video: "4K/60fps", "Flight time": "34 min", Serial: "Checked" } },
  { slug: "dji-mini-2", category: "gadgets", brand: "DJI", name: "DJI Mini 2", photo: "DJI_Mini_2.jpg", art: "drone", tint: "#8a8c8f", price: 520_000, stock: 1, tiers: [s("Fly More Combo", 0)], attrs: { Video: "4K/30fps", "Flight time": "31 min", Serial: "Checked" } },
  { slug: "dji-mavic-air-2", category: "gadgets", brand: "DJI", name: "DJI Mavic Air 2", photo: "DJI_Mavic_Air_2.jpg", art: "drone", tint: "#5f6266", price: 780_000, stock: 1, tiers: [s("Standard", 0)], attrs: { Video: "4K/60fps", "Flight time": "34 min", Serial: "Checked" } },
  { slug: "dji-osmo-pocket-3", category: "gadgets", brand: "DJI", name: "DJI Osmo Pocket 3", photo: "DJI_Osmo_Pocket_3_-_4.jpg", art: "camera", tint: "#1b1b1b", price: 720_000, stock: 1, tiers: [s("Standard", 0), s("Creator Combo", 180_000)], attrs: { Sensor: '1" CMOS', Video: "4K/120fps", Serial: "Checked" } },
  { slug: "canon-eos-r50", category: "gadgets", brand: "Canon", name: "Canon EOS R50", photo: "Canon_EOS_R50,_White,_6.jpg", art: "camera", tint: "#f2f2f2", price: 980_000, stock: 2, tiers: [s("RF-S 18-45mm kit", 0)], colors: ["White", "Black"], attrs: { Sensor: "24.2MP APS-C", Video: "4K/30fps", Serial: "Checked" } },
  { slug: "canon-eos-r6-ii", category: "gadgets", brand: "Canon", name: "Canon EOS R6 Mark II", photo: "Canon_EOS_R6_Mark_II_-_by_Henry_Söderlund_(52546794891).jpg", art: "camera", tint: "#1b1b1b", price: 3_200_000, stock: 1, tiers: [s("Body only", 0), s("RF 24-105mm kit", 900_000)], attrs: { Sensor: "24.2MP full frame", Video: "4K/60fps", Serial: "Checked" } },
  { slug: "sony-a7-iv", category: "gadgets", brand: "Sony", name: "Sony A7 IV", photo: "Sony_A7_IV_(ILCE-7M4)_-_by_Henry_Söderlund_(51739988735).jpg", art: "camera", tint: "#1b1b1b", price: 3_500_000, stock: 1, tiers: [s("Body only", 0), s("FE 28-70mm kit", 350_000)], attrs: { Sensor: "33MP full frame", Video: "4K/60fps", Serial: "Checked" } },

  // ------------------------------------------------------------------ Cars
  { slug: "toyota-camry-2018-se", category: "cars", brand: "Toyota", name: "Toyota Camry SE", photo: "Toyota_Camry_(XV70)_SE_(2),_United_States.jpg", art: "car", tint: "#9c9fa3", price: 24_000_000, stock: 3, car: { year: 2018, km: [55_000, 98_000], origin: "Foreign used", engine: "2.5L 4-cyl" } },
  { slug: "toyota-camry-2019-xse", category: "cars", brand: "Toyota", name: "Toyota Camry XSE", photo: "Toyota_Camry_(XV70)_XSE.jpg", art: "car", tint: "#7a1f24", price: 28_000_000, stock: 2, car: { year: 2019, km: [40_000, 80_000], origin: "Foreign used", engine: "2.5L 4-cyl" } },
  { slug: "toyota-camry-2012-se", category: "cars", brand: "Toyota", name: "Toyota Camry SE V6", photo: "2012_Toyota_Camry_SE_V6_XV50_Sedan.jpg", art: "car", tint: "#f1f1f1", price: 10_000_000, stock: 2, car: { year: 2012, km: [110_000, 165_000], origin: "Nigerian used", engine: "3.5L V6" } },
  { slug: "toyota-camry-2014", category: "cars", brand: "Toyota", name: "Toyota Camry V6", photo: "Toyota_Camry_XV50_Brasil_SAO_2014_0402.JPG", art: "car", tint: "#2b2b2b", price: 12_500_000, stock: 2, car: { year: 2014, km: [90_000, 140_000], origin: "Foreign used", engine: "3.5L V6" } },
  { slug: "toyota-corolla-2016", category: "cars", brand: "Toyota", name: "Toyota Corolla LE", photo: "Toyota_Corolla_2016_Model.jpg", art: "car", tint: "#9c9fa3", price: 9_500_000, stock: 2, car: { year: 2016, km: [80_000, 130_000], origin: "Foreign used", engine: "1.8L 4-cyl" } },
  { slug: "toyota-corolla-2020-hybrid", category: "cars", brand: "Toyota", name: "Toyota Corolla Hybrid", photo: "Toyota_Corolla_sedan_E210_hydrid.jpg", art: "car", tint: "#f1f1f1", price: 17_000_000, stock: 2, car: { year: 2020, km: [35_000, 70_000], origin: "Foreign used", engine: "1.8L Hybrid" } },
  { slug: "toyota-highlander-2016", category: "cars", brand: "Toyota", name: "Toyota Highlander Limited", photo: "Toyota_Highlander_XU50.jpg", art: "car", tint: "#1e2a38", price: 26_500_000, stock: 2, car: { year: 2016, km: [70_000, 120_000], origin: "Foreign used", engine: "3.5L V6" } },
  { slug: "toyota-rav4-2019", category: "cars", brand: "Toyota", name: "Toyota RAV4 XLE", photo: "Toyota_rav4_xa50_grey_(1).jpg", art: "car", tint: "#6b6e72", price: 25_000_000, stock: 2, car: { year: 2019, km: [45_000, 85_000], origin: "Foreign used", engine: "2.5L 4-cyl" } },
  { slug: "toyota-venza-2010", category: "cars", brand: "Toyota", name: "Toyota Venza", photo: "Toyota_Venza_--_10-20-2010.jpg", art: "car", tint: "#3b3f46", price: 10_500_000, stock: 2, car: { year: 2010, km: [120_000, 170_000], origin: "Nigerian used", engine: "3.5L V6" } },
  { slug: "toyota-sienna-2012", category: "cars", brand: "Toyota", name: "Toyota Sienna LE", photo: "Toyota_Sienna_LE_(6222546663).jpg", art: "car", tint: "#9c9fa3", price: 11_000_000, stock: 2, car: { year: 2012, km: [115_000, 160_000], origin: "Foreign used", engine: "3.5L V6" } },
  { slug: "toyota-prado-2014", category: "cars", brand: "Toyota", name: "Toyota Land Cruiser Prado", photo: "Toyota_Land_Cruiser_Prado_150.jpg", art: "car", tint: "#f1f1f1", price: 38_000_000, stock: 1, car: { year: 2014, km: [95_000, 140_000], origin: "Foreign used", engine: "4.0L V6" } },
  { slug: "toyota-hilux-2018", category: "cars", brand: "Toyota", name: "Toyota Hilux", photo: "Toyota_HiLux_AN120-AN130_Single_Cab.jpg", art: "car", tint: "#f1f1f1", price: 32_000_000, stock: 1, car: { year: 2018, km: [60_000, 110_000], origin: "Nigerian used", engine: "2.7L 4-cyl" } },
  { slug: "lexus-rx350-2016", category: "cars", brand: "Lexus", name: "Lexus RX 350", photo: "Lexus_RX_AL20_01_China_2016-04-16.jpg", art: "car", tint: "#1e2a38", price: 30_000_000, stock: 3, car: { year: 2016, km: [60_000, 110_000], origin: "Foreign used", engine: "3.5L V6" } },
  { slug: "lexus-es350-2019", category: "cars", brand: "Lexus", name: "Lexus ES 350", photo: "2019_Lexus_ES_350,_front_11.9.19.jpg", art: "car", tint: "#f1f1f1", price: 33_000_000, stock: 2, car: { year: 2019, km: [35_000, 75_000], origin: "Foreign used", engine: "3.5L V6" } },
  { slug: "lexus-gx460-2015", category: "cars", brand: "Lexus", name: "Lexus GX 460", photo: "Lexus_GX_460_URJ150_Sonic_Quartz_-_front.jpg", art: "car", tint: "#f1f1f1", price: 42_000_000, stock: 1, car: { year: 2015, km: [80_000, 125_000], origin: "Foreign used", engine: "4.6L V8" } },
  { slug: "honda-accord-2018", category: "cars", brand: "Honda", name: "Honda Accord EX", photo: "2018_Honda_Accord_front_4.1.18.jpg", art: "car", tint: "#7a1f24", price: 19_500_000, stock: 2, car: { year: 2018, km: [55_000, 95_000], origin: "Foreign used", engine: "1.5L Turbo" } },
  { slug: "honda-crv-2018", category: "cars", brand: "Honda", name: "Honda CR-V EX", photo: "Honda_CR-V_Genf_2018.jpg", art: "car", tint: "#6b6e72", price: 21_000_000, stock: 2, car: { year: 2018, km: [50_000, 95_000], origin: "Foreign used", engine: "1.5L Turbo" } },
  { slug: "mercedes-c300-2019", category: "cars", brand: "Mercedes-Benz", name: "Mercedes-Benz C 300", photo: "Mercedes-Benz_C-Class_W205_FL_silver_(1).jpg", art: "car", tint: "#c0c3c8", price: 26_000_000, stock: 2, car: { year: 2019, km: [40_000, 85_000], origin: "Foreign used", engine: "2.0L Turbo" } },
  { slug: "mercedes-glk350-2012", category: "cars", brand: "Mercedes-Benz", name: "Mercedes-Benz GLK 350", photo: "2010_white_Mercedes_GLK_350_front.JPG", art: "car", tint: "#f1f1f1", price: 13_500_000, stock: 2, car: { year: 2012, km: [100_000, 150_000], origin: "Nigerian used", engine: "3.5L V6" } },
  { slug: "mercedes-gle350-2020", category: "cars", brand: "Mercedes-Benz", name: "Mercedes-Benz GLE 350", photo: "Mercedes-Benz_GLE_350_d_4MATIC_AMG_Line_(V_167)_–_h_09022020.jpg", art: "car", tint: "#1f1f1f", price: 55_000_000, stock: 1, car: { year: 2020, km: [30_000, 65_000], origin: "Foreign used", engine: "2.0L Turbo" } },
  { slug: "hyundai-elantra-2018", category: "cars", brand: "Hyundai", name: "Hyundai Elantra Sport", photo: "Hyundai_Elantra_Sport_P4250858.jpg", art: "car", tint: "#9c9fa3", price: 9_800_000, stock: 2, car: { year: 2018, km: [70_000, 115_000], origin: "Foreign used", engine: "1.6L Turbo" } },
  { slug: "hyundai-tucson-2017", category: "cars", brand: "Hyundai", name: "Hyundai Tucson", photo: "Hyundai_Tucson_TL.jpg", art: "car", tint: "#f1f1f1", price: 13_500_000, stock: 2, car: { year: 2017, km: [75_000, 120_000], origin: "Foreign used", engine: "2.0L 4-cyl" } },
  { slug: "kia-sportage-2018", category: "cars", brand: "Kia", name: "Kia Sportage Si", photo: "2018_Kia_Sportage_(QL_MY18)_Si_wagon_(2018-11-02)_01.jpg", art: "car", tint: "#f1f1f1", price: 14_000_000, stock: 2, car: { year: 2018, km: [65_000, 110_000], origin: "Foreign used", engine: "2.4L 4-cyl" } },
  { slug: "ford-explorer-2016", category: "cars", brand: "Ford", name: "Ford Explorer XLT", photo: "Ford_Explorer_flexfuel_CRI_07_2016_7706.jpg", art: "car", tint: "#1f1f1f", price: 15_500_000, stock: 2, car: { year: 2016, km: [85_000, 135_000], origin: "Foreign used", engine: "3.5L V6" } },
];
